import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { content } = await request.json();

    console.log('Received request with content length:', content?.length);

    if (!content || typeof content !== 'string') {
      return NextResponse.json(
        { error: 'Content is required and must be a string' },
        { status: 400 }
      );
    }

    // Check if OpenAI API key is configured
    if (!process.env.OPENAI_API_KEY) {
      console.log('OPENAI_API_KEY missing:', process.env.OPENAI_API_KEY ? 'Exists' : 'Missing');
      return NextResponse.json(
        { error: 'OpenAI API key not configured' },
        { status: 500 }
      );
    }

    // Import OpenAI dynamically to avoid build issues
    const { default: OpenAI } = await import('openai');

    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });

    const truncatedContent = content.slice(0, 12000);

    const completion = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content: `You are a helpful assistant that summarizes content concisely and accurately. 
          Provide key points and main ideas in a clear, structured way. 
          Keep the summary under 200 words while maintaining the core message and important details.`
        },
        {
          role: "user",
          content: `Please summarize the following content:\n\n${truncatedContent}`
        }
      ],
      max_tokens: 300,
      temperature: 0.7,
    });

    const summary = completion.choices[0].message.content;

    if (!summary) {
      throw new Error('No summary generated by AI');
    }

    return NextResponse.json({ summary });

  } catch (error: any) {
    console.error('API Route Error:', error);
    
    // Provide more specific error messages
    let errorMessage = 'Failed to generate summary';
    let statusCode = 500;

    if (error?.code === 'invalid_api_key') {
      errorMessage = 'Invalid OpenAI API key';
      statusCode = 401;
    } else if (error?.code === 'insufficient_quota') {
      errorMessage = 'OpenAI API quota exceeded';
      statusCode = 429;
    } else if (error?.message?.includes('API key')) {
      errorMessage = 'OpenAI API key issue - please check your configuration';
      statusCode = 401;
    }

    return NextResponse.json(
      { error: errorMessage, details: error?.message },
      { status: statusCode }
    );
  }
}